services:
  # 1. Backend API Service
  - type: web
    name: the-courtyard-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

      # Database
      - key: MONGODB_URI
        value: mongodb://hardik:hardik1231H@ac-bl4k2sr-shard-00-00.hjn75wd.mongodb.net:27017,ac-bl4k2sr-shard-00-01.hjn75wd.mongodb.net:27017,ac-bl4k2sr-shard-00-02.hjn75wd.mongodb.net:27017/the-courtyard?ssl=true&authSource=admin

      # Auth
      - key: JWT_SECRET
        value: the_courtyard_jwt_secret_key_2026_premium

      # Email — Resend (Primary, HTTP API, works on Render)
      - key: RESEND_API_KEY
        value: re_9N2LhYUe_G1MxkRj54ErY5sjgDNK4cfVr

      # Email — SMTP Gmail (Fallback, works locally)
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        value: gamingl3ad3r@gmail.com
      - key: SMTP_PASS
        value: fpouklycfrwycwar
      - key: SMTP_FROM_EMAIL
        value: gamingl3ad3r@gmail.com
      - key: SMTP_FROM_NAME
        value: The Courtyard

  # 2. Frontend Next.js Client
  - type: web
    name: the-courtyard-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://the-courtyard-backend.onrender.com/api
